blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/didimozg/AD_Server_Local_Group_Report/security
    about: Please report sensitive security issues privately first.
